
/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @generated by codegen project: GenerateShadowNodeH.js
 */

#pragma once

#include <react/renderer/components/Wishlist/EventEmitters.h>
#include <react/renderer/components/Wishlist/Props.h>
#include <react/renderer/components/view/ConcreteViewShadowNode.h>

namespace facebook {
namespace react {

extern const char MGWishListComponentComponentName[];

/*
 * `ShadowNode` for <MGWishListComponent> component.
 */
using MGWishListComponentShadowNode = ConcreteViewShadowNode<
    MGWishListComponentComponentName,
    MGWishListComponentProps,
MGWishListComponentEventEmitter>;

} // namespace react
} // namespace facebook
