
/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @generated by codegen project: GeneratePropsH.js
 */
#pragma once

#include <react/renderer/components/view/ViewProps.h>
#include <react/renderer/core/ShadowNode.h>
#include <react/renderer/core/PropsParserContext.h>
#include "MGContainerProps.h"

namespace facebook {
namespace react {

struct MGTemplateContainerComponentProps final : public ViewProps {
 public:
  MGTemplateContainerComponentProps() = default;
  MGTemplateContainerComponentProps(const PropsParserContext& context, const MGTemplateContainerComponentProps &sourceProps, const RawProps &rawProps);
  

#pragma mark - Props

  std::string inflatorId{};
  std::vector<std::string> names{};
  std::vector<std::shared_ptr<ShadowNode const>> templates;
};

} // namespace react
} // namespace facebook
