/**
* Copyright (c) Facebook, Inc. and its affiliates.
*
* This source code is licensed under the MIT license found in the
* LICENSE file in the root directory of this source tree.
*
* @generated by codegen project: GeneratePropsJavaDelegate.js
*/

package com.facebook.react.viewmanagers;

import android.view.View;
import androidx.annotation.Nullable;
import com.facebook.react.bridge.ReadableArray;
import com.facebook.react.uimanager.BaseViewManagerDelegate;
import com.facebook.react.uimanager.BaseViewManagerInterface;

public class MGWishListComponentManagerDelegate<T extends View, U extends BaseViewManagerInterface<T> & MGWishListComponentManagerInterface<T>> extends BaseViewManagerDelegate<T, U> {
  public MGWishListComponentManagerDelegate(U viewManager) {
    super(viewManager);
  }
  @Override
  public void setProperty(T view, String propName, @Nullable Object value) {
    switch (propName) {
      case "kkk":
        mViewManager.setKkk(view, value == null ? 0 : ((Double) value).intValue());
        break;
      case "inflatorId":
        mViewManager.setInflatorId(view, value == null ? null : (String) value);
        break;
      case "names":
        mViewManager.setNames(view, (ReadableArray) value);
        break;
      default:
        super.setProperty(view, propName, value);
    }
  }

  @Override
  public void receiveCommand(T view, String commandName, ReadableArray args) {
    switch (commandName) {
      case "scrollTo":
        mViewManager.scrollTo(view, args.getInt(0), args.getBoolean(1));
        break;
    }
  }
}
