/**
* Copyright (c) Facebook, Inc. and its affiliates.
*
* This source code is licensed under the MIT license found in the
* LICENSE file in the root directory of this source tree.
*
* @generated by codegen project: GeneratePropsJavaInterface.js
*/

package com.facebook.react.viewmanagers;

import android.view.View;
import androidx.annotation.Nullable;
import com.facebook.react.bridge.ReadableArray;

public interface MGWishListComponentManagerInterface<T extends View> {
  void setKkk(T view, int value);
  void setInflatorId(T view, @Nullable String value);
  void setNames(T view, @Nullable ReadableArray value);
  void scrollTo(T view, int y, boolean animated);
}
