
/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @generated by codegen project: GeneratePropsCpp.js
 */

#include <react/renderer/components/Wishlist/Props.h>
#include <react/renderer/core/PropsParserContext.h>
#include <react/renderer/core/propsConversions.h>

namespace facebook {
namespace react {

MGWishListComponentProps::MGWishListComponentProps(
    const PropsParserContext &context,
    const MGWishListComponentProps &sourceProps,
    const RawProps &rawProps): ViewProps(context, sourceProps, rawProps),

    kkk(convertRawProp(context, rawProps, "kkk", sourceProps.kkk, {0})),
    inflatorId(convertRawProp(context, rawProps, "inflatorId", sourceProps.inflatorId, {})),
    names(convertRawProp(context, rawProps, "names", sourceProps.names, {}))
      {}

} // namespace react
} // namespace facebook
