/**
* Copyright (c) Facebook, Inc. and its affiliates.
*
* This source code is licensed under the MIT license found in the
* LICENSE file in the root directory of this source tree.
*
* @generated by codegen project: GeneratePropsJavaInterface.js
*/

package com.margelo.wishlist;

import android.view.View;

public interface WishlistManagerInterface<T extends View> {
  // No props
  void scrollTo(T view, int y, boolean animated);
}
