
/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @generated by codegen project: GenerateComponentDescriptorH.js
 */

#pragma once

#include "WishlistShadowNodes.h"
#include <react/renderer/core/ConcreteComponentDescriptor.h>

namespace facebook {
namespace react {

class WishlistComponentDescriptor : public ConcreteComponentDescriptor<WishlistShadowNode> {
public:
    WishlistComponentDescriptor(ComponentDescriptorParameters const &parameters): ConcreteComponentDescriptor(parameters) {
        
    }
    
    // TODO think about it 
    virtual ShadowNode::Shared createShadowNode(
        const ShadowNodeFragment &fragment,
        ShadowNodeFamily::Shared const &family) const override {
        
        auto shadowNode =
            std::make_shared<WishlistShadowNode>(ShadowNodeFragment{fragment.props, nullptr, fragment.state}, family, getTraits());
        ShadowNode::SharedListOfShared registeredComponents = fragment.children;
        shadowNode->sharedThis = shadowNode;
            //
          /*  for (std::shared_ptr<const ShadowNode> sn : (*(fragment.children))) {
                int x = 5;
                int y = x;
            }*/
            //const std::shared_ptr<const ShadowNode> sn = fragment.children[0];
            
            //
      adopt(shadowNode);

      return shadowNode;
    }
    
    // TODO fix this
    virtual ShadowNode::Unshared cloneShadowNode(
        const ShadowNode &sourceShadowNode,
        const ShadowNodeFragment &fragment) const override {
        
        ShadowNode::Unshared shadowNode(nullptr);
        if (ViewportObserver::isPushingChildren) {
            shadowNode = std::make_shared<WishlistShadowNode>(sourceShadowNode, fragment);
        } else {
            shadowNode = std::make_shared<WishlistShadowNode>(sourceShadowNode, ShadowNodeFragment{});
        }
        
        std::shared_ptr<WishlistShadowNode> wishlistShadowNode = std::static_pointer_cast<WishlistShadowNode>(shadowNode);
        wishlistShadowNode->registeredViews = static_cast<const WishlistShadowNode&>(sourceShadowNode).registeredViews;
            wishlistShadowNode->sharedThis = wishlistShadowNode;

        adopt(shadowNode);
        return shadowNode;
    }
    
    virtual ~WishlistComponentDescriptor(){}
};


} // namespace react
} // namespace facebook
