
/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @generated by codegen project: GenerateEventEmitterH.js
 */
#pragma once

#include <react/renderer/components/view/ViewEventEmitter.h>

namespace facebook {
namespace react {

class WishlistEventEmitter : public ViewEventEmitter {
 public:
  using ViewEventEmitter::ViewEventEmitter;

  struct OnStartReached {
      
    };

  struct OnEndReached {
      
    };

  void onStartReached(OnStartReached value) const;

  void onEndReached(OnEndReached value) const;
};

} // namespace react
} // namespace facebook
