
/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @generated by codegen project: GenerateEventEmitterCpp.js
 */

#include "WishlistEventEmitters.h"

namespace facebook {
namespace react {

void WishlistEventEmitter::onStartReached(OnStartReached event) const {
  dispatchEvent(
      "startReached", [event = std::move(event)](jsi::Runtime &runtime) {
        auto payload = jsi::Object(runtime);

        return payload;
      });
}
void WishlistEventEmitter::onEndReached(OnEndReached event) const {
  dispatchEvent(
      "endReached", [event = std::move(event)](jsi::Runtime &runtime) {
        auto payload = jsi::Object(runtime);

        return payload;
      });
}

} // namespace react
} // namespace facebook
