
/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @generated by codegen project: GenerateShadowNodeH.js
 */

#pragma once

#include "MGInterceptorProps.h"
#include <react/renderer/components/view/ConcreteViewShadowNode.h>

namespace facebook {
namespace react {

extern const char MGTemplateInterceptorComponentComponentName[];

/*
 * `ShadowNode` for <MGTemplateInterceptorComponent> component.
 */
using MGTemplateInterceptorComponentShadowNode = ConcreteViewShadowNode<
    MGTemplateInterceptorComponentComponentName,
    MGTemplateInterceptorComponentProps>;

} // namespace react
} // namespace facebook
