
/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @generated by codegen project: GeneratePropsCpp.js
 */

#include <react/renderer/components/Wishlist/Props.h>
#include <react/renderer/core/PropsParserContext.h>
#include <react/renderer/core/propsConversions.h>

namespace facebook {
namespace react {

MGTemplateInterceptorComponentProps::MGTemplateInterceptorComponentProps(
    const PropsParserContext &context,
    const MGTemplateInterceptorComponentProps &sourceProps,
    const RawProps &rawProps): ViewProps(context, sourceProps, rawProps),

    inflatorId(convertRawProp(context, rawProps, "inflatorId", sourceProps.inflatorId, {}))
      {}

} // namespace react
} // namespace facebook
