
/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @generated by codegen project: GenerateShadowNodeCpp.js
 */

#include "ModuleShadowNodes.h"

namespace facebook {
namespace react {

extern const char ModuleComponentName[] = "MGWishListComponent";

} // namespace react
} // namespace facebook
