
/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @generated by codegen project: GeneratePropsCpp.js
 */

#include "ModuleProps.h"
#include <react/renderer/core/PropsParserContext.h>
#include <react/renderer/core/propsConversions.h>

namespace facebook {
namespace react {

ModuleProps::ModuleProps(
    const PropsParserContext &context,
    const ModuleProps &sourceProps,
    const RawProps &rawProps): ViewProps(context, sourceProps, rawProps),
    kkk(convertRawProp(context, rawProps, "kkk", sourceProps.kkk, 1)),
    inflatorId(convertRawProp(context, rawProps, "inflatorId", sourceProps.inflatorId, "__defaultId__")),
    names(convertRawProp(context, rawProps, "names", sourceProps.names, {}))
      {
          int x = 4;
      }

} // namespace react
} // namespace facebook
