
/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @generated by codegen project: GeneratePropsH.js
 */
#pragma once

#include <react/renderer/components/view/ViewProps.h>
#include <react/renderer/core/PropsParserContext.h>
#include <vector>

namespace facebook {
namespace react {

class ModuleProps final : public ViewProps {
 public:
  ModuleProps() = default;
  ModuleProps(const PropsParserContext& context, const ModuleProps &sourceProps, const RawProps &rawProps);

#pragma mark - Props

  std::vector<std::string> names{};
};

} // namespace react
} // namespace facebook
