
/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @generated by codegen project: GeneratePropsCpp.js
 */

#include "MGContainerProps.h"
#include <react/renderer/components/view/ViewProps.h>
#include <react/renderer/core/PropsParserContext.h>
#include <react/renderer/core/propsConversions.h>

namespace facebook {
namespace react {

MGTemplateContainerComponentProps::MGTemplateContainerComponentProps(
    const PropsParserContext &context,
    const MGTemplateContainerComponentProps &sourceProps,
    const RawProps &rawProps)
    : ViewProps(context, sourceProps, rawProps),
      names(convertRawProp(context, rawProps, "names", sourceProps.names, {})),
      inflatorId(convertRawProp(
          context,
          rawProps,
          "inflatorId",
          sourceProps.inflatorId,
          {})),
                 wishlistId(convertRawProp(
                     context,
                     rawProps,
                     "wishlistId",
                     sourceProps.wishlistId,
                     {})) {
  templates = sourceProps.templates;
}

} // namespace react
} // namespace facebook
