
/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @generated by codegen project: GenerateShadowNodeH.js
 */

#pragma once

#include <react/renderer/components/view/ConcreteViewShadowNode.h>
#include "LayoutContext.h"
#include "MGContainerProps.h"

namespace facebook {
namespace react {

extern const char MGTemplateContainerComponentComponentName[];

/*
 * `ShadowNode` for <MGTemplateContainerComponent> component.
 */
struct MGTemplateContainerComponentShadowNode
    : public ConcreteViewShadowNode<
          MGTemplateContainerComponentComponentName,
          MGTemplateContainerComponentProps> {
  std::vector<std::shared_ptr<ShadowNode const>> templates;

  MGTemplateContainerComponentShadowNode(
      ShadowNodeFragment const &fragment,
      ShadowNodeFamily::Shared const &family,
      ShadowNodeTraits traits);

  MGTemplateContainerComponentShadowNode(
      ShadowNode const &sourceShadowNode,
      ShadowNodeFragment const &fragment);

  void appendChild(ShadowNode::Shared const &childNode);

  void layout(LayoutContext layoutContext);

  virtual ~MGTemplateContainerComponentShadowNode() {}
};

} // namespace react
} // namespace facebook
