
/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @generated by codegen project: GeneratePropsH.js
 */
#pragma once

#include <react/renderer/components/view/ViewProps.h>
#include <react/renderer/core/PropsParserContext.h>
#include <vector>

namespace facebook {
namespace react {

class WishlistProps final : public ViewProps {
 public:
  WishlistProps() = default;
  WishlistProps(
      const PropsParserContext &context,
      const WishlistProps &sourceProps,
      const RawProps &rawProps);

#pragma mark - Props

  int initialIndex;
  std::string inflatorId;
  std::vector<std::string> names{};
};

} // namespace react
} // namespace facebook
